# Generated by Django 4.2.29 on 2026-03-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.CharField(max_length=255)),
                ('normalized_query', models.CharField(max_length=255)),
                ('query_hash', models.CharField(max_length=64, unique=True)),
                ('hit_count', models.PositiveBigIntegerField(default=0)),
                ('last_requested_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_place_id', models.CharField(max_length=255, unique=True)),
                ('formatted_address', models.CharField(db_index=True, max_length=512)),
                ('normalized_formatted_address', models.CharField(db_index=True, max_length=512)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('location_type', models.CharField(blank=True, max_length=64)),
                ('partial_match', models.BooleanField(default=False)),
                ('address_components', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance_meters', models.DecimalField(decimal_places=3, max_digits=15)),
                ('hit_count', models.PositiveBigIntegerField(default=0)),
                ('last_requested_at', models.DateTimeField(auto_now=True)),
                ('destination_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='geodata.place')),
                ('origin_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='geodata.place')),
            ],
        ),
        migrations.CreateModel(
            name='ReverseGeocodeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('latitude_e6', models.BigIntegerField()),
                ('longitude_e6', models.BigIntegerField()),
                ('hit_count', models.PositiveBigIntegerField(default=0)),
                ('last_requested_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_lookups', to='geodata.place')),
            ],
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['normalized_formatted_address'], name='place_norm_addr_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='place_lat_lng_idx'),
        ),
        migrations.AddField(
            model_name='geocodelookup',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_lookups', to='geodata.place'),
        ),
        migrations.AddIndex(
            model_name='routedistance',
            index=models.Index(fields=['origin_place', 'destination_place', 'last_requested_at'], name='route_origin_dest_req_idx'),
        ),
        migrations.AddConstraint(
            model_name='routedistance',
            constraint=models.UniqueConstraint(fields=('origin_place', 'destination_place'), name='route_origin_destination_uniq'),
        ),
        migrations.AddIndex(
            model_name='reversegeocodelookup',
            index=models.Index(fields=['place', 'last_requested_at'], name='reverse_place_req_idx'),
        ),
        migrations.AddConstraint(
            model_name='reversegeocodelookup',
            constraint=models.UniqueConstraint(fields=('latitude_e6', 'longitude_e6'), name='reverse_lookup_latlng_e6_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reversegeocodelookup',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='reverse_lookup_lat_valid'),
        ),
        migrations.AddConstraint(
            model_name='reversegeocodelookup',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='reverse_lookup_lng_valid'),
        ),
        migrations.AddIndex(
            model_name='geocodelookup',
            index=models.Index(fields=['normalized_query'], name='geocode_norm_query_idx'),
        ),
        migrations.AddIndex(
            model_name='geocodelookup',
            index=models.Index(fields=['place', 'last_requested_at'], name='geocode_place_req_idx'),
        ),
    ]
